name: "184574"
on:
  push:
    branches:
      - main
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t my-image:latest .
      - name: Scan Docker image for vulnerabilities
        uses: aquasecurity/trivy-action@v0.11.0
        with:
          image-ref: my-image:latest
          format: table
